use_frameworks!

platform :ios, '8.0'

target 'SLFirstFrame_Example' do
  pod 'SLFirstFrame', :path => '../'

  target 'SLFirstFrame_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
